insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 2,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 4,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 5,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 3,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 2,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 2,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 2,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 2,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 2,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 2,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 3,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 5,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 4,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 4,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 3,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 2,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 2,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 3,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 4,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 4,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 5,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 2,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 2,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 2,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 2,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 2,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 3,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 3,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 3,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 3,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 4,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 4,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 4,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 4,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 4,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 5,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 5,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 5,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 5,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 5,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 1,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 6,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 6,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 6,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 6,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 5,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 4,'Kong vungsovanreach','this is the crazy book','democover.png')
insert into tb_articles(title,category_id,author,description,thumbnail) values('hello its me', 3,'Kong vungsovanreach','this is the crazy book','democover.png')


insert into tb_categories(title) values('Romaticism')
insert into tb_categories(title) values('Novelism')
insert into tb_categories(title) values('Friendzonism')
insert into tb_categories(title) values('Crazyism')
insert into tb_categories(title) values('Lovelyism')
insert into tb_categories(title) values('Stupidism')
insert into tb_categories(title) values('Adorablism')


insert into tb_users(username, password, name,gender,status) values ('admin','$2a$10$Kt6f65yzUyTtS9xPr2kD9eDI1BUiFEi0ZuGrypGiOP.WD.O2HLjtq','Bong Admin','male','true')
insert into tb_users(username, password, name,gender,status) values ('user','$2a$10$jE6vajpviT7LuMALAD/K.OhER4eXnVALHXaOpt7NF0tN1OUdfkCyO','Bong User','female','true')


insert into tb_roles(role) values ('ADMIN')
insert into tb_roles(role) values ('USER')


insert into tb_user_roles values (1,1)
insert into tb_user_roles values (2,2)